// vite-solid-typescript/src/App.tsx
import { createSignal } from 'solid-js'
import Ably from 'ably/promises'
import solidLogo from './assets/solid.svg'
import viteLogo from '/vite.svg'
import ablyLogo from './assets/ably-motif-col-rgb.svg'
import './App.css'

function App() {
  const [count, setCount] = createSignal(0)

  const client = new Ably.Realtime.Promise({ authUrl: '/api/ably/token/' });

  const [state, setState] = createSignal('')
  client.connection.on((stateChange:Ably.Types.ConnectionStateChange) => {
    setState(stateChange.current);
  });

  return (
    <>
      <div>
        <a href="https://vitejs.dev" target="_blank">
          <img src={viteLogo} class="logo" alt="Vite logo" />
        </a>
        <a href="https://solidjs.com" target="_blank">
          <img src={solidLogo} class="logo solid" alt="Solid logo" />
        </a>
        <a href="https://ably.com" target="_blank">
          <img src={ablyLogo} class="logo ably" alt="Ably logo" />
        </a>
      </div>
      <h1>Vite + Solid + Ably</h1>
      <div class="card">
      <p><span>Realtime Connection Status: {state()}</span></p>
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count()}
        </button>
        <p>
          Edit <code>src/App.jsx</code> and save to test HMR
        </p>
      </div>
      <p class="read-the-docs">
        Click on the Vite, Solid and Ably logos to learn more
      </p>
    </>
  )
}

export default App

// vite-svelte-typescript/src/App.svelte
<script lang="ts">
  import Ably from 'ably/promises'
  import svelteLogo from './assets/svelte.svg'
  import viteLogo from '/vite.svg'
  import ablyLogo from './assets/ably-motif-col-rgb.svg'
  import Counter from './lib/Counter.svelte'

  const client = new Ably.Realtime.Promise({ authUrl: '/api/ably/token/' });

  let state = '';
  client.connection.on((stateChange:Ably.Types.ConnectionStateChange) => {
    state = stateChange.current;
  });
</script>


<main>
  <div>
    <a href="https://vitejs.dev" target="_blank" rel="noreferrer">
      <img src={viteLogo} class="logo" alt="Vite Logo" />
    </a>
    <a href="https://svelte.dev" target="_blank" rel="noreferrer">
      <img src={svelteLogo} class="logo svelte" alt="Svelte Logo" />
    </a>
    <a href="https://ably.com" target="_blank" rel="noreferrer">
      <img src={ablyLogo} class="logo ably" alt="Ably Logo" />
    </a>
  </div>
  <h1>Vite + Svelte + Ably</h1>

  <div class="card">
    <p><span>Realtime Connection Status: {state}</span></p>
    <Counter />
  </div>

  <p>
    Check out <a href="https://github.com/sveltejs/kit#readme" target="_blank" rel="noreferrer">SvelteKit</a>, the official Svelte app framework powered by Vite!
  </p>

  <p class="read-the-docs">
    Click on the Vite and Svelte logos to learn more
  </p>
</main>

<style>
  .logo {
    height: 6em;
    padding: 1.5em;
    will-change: filter;
    transition: filter 300ms;
  }
  .logo:hover {
    filter: drop-shadow(0 0 2em #646cffaa);
  }
  .logo.svelte:hover {
    filter: drop-shadow(0 0 2em #ff3e00aa);
  }
  .read-the-docs {
    color: #888;
  }
</style>
